<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->

In [1]:
#| echo: false
#| output: asis
show_doc(ForensicFace)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/forensicface.py#L7){target="_blank" style="float:right; font-size:smaller"}

### ForensicFace

>      ForensicFace (model:str='sepaelv2', det_size:int=320, use_gpu:bool=True,
>                    gpu:int=0, extended=True)

Class for processing facial images to extract useful features for forensic analysis.

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| model | str | sepaelv2 |  |
| det_size | int | 320 |  |
| use_gpu | bool | True |  |
| gpu | int | 0 | which GPU to use |
| extended | bool | True |  |

In [ ]:
ff = ForensicFace(use_gpu=True, extended=True)

Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /home/rafael/.insightface/models/sepaelv2/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cud

In [ ]:
result = ff.process_image_single_face("001_frontal.jpg")
result.keys(), result["keypoints"], result["ipd"], result["embedding"].shape

/home/rafael/miniconda3/envs/ffdev/lib/python3.10/site-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


(dict_keys(['keypoints', 'ipd', 'embedding', 'norm', 'bbox', 'aligned_face', 'gender', 'age', 'pitch', 'yaw', 'roll', 'fiqa_score']),
 array([[467.3665 , 681.6384 ],
        [772.4218 , 677.03107],
        [625.37726, 836.4494 ],
        [504.2984 , 992.18964],
        [751.0406 , 985.683  ]], dtype=float32),
 305.09012,
 (512,))

In [ ]:
results = ff.process_image_multiple_faces("tela.png")
results[0].keys(), results[0]["keypoints"], results[0]["bbox"]

(dict_keys(['keypoints', 'ipd', 'embedding', 'norm', 'bbox', 'aligned_face', 'gender', 'age', 'pitch', 'yaw', 'roll', 'fiqa_score']),
 array([[471.42743, 418.60498],
        [522.68933, 418.05362],
        [498.82196, 449.08923],
        [479.3499 , 476.44193],
        [514.33453, 476.06885]], dtype=float32),
 array([441, 355, 548, 506]))

## Comparação entre duas imagens

In [2]:
#| echo: false
#| output: asis
show_doc(ForensicFace.compare)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/app.py#L390){target="_blank" style="float:right; font-size:smaller"}

### ForensicFace.compare

>      ForensicFace.compare (img1path:str, img2path:str)

Compares the similarity between two face images based on their embeddings.

Parameters:
    - img1path (str): Path to the first image file
    - img2path (str): Path to the second image file

Returns:
    A float representing the similarity score between the two faces based on their embeddings.
    The score ranges from -1.0 to 1.0, where 1.0 represents a perfect match and -1.0 represents a complete mismatch.

In [ ]:
ff.compare("obama.png", "obama2.png")

0.85562766

## Agregação de embeddings

In [3]:
#| echo: false
#| output: asis
show_doc(ForensicFace.aggregate_embeddings)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/app.py#L412){target="_blank" style="float:right; font-size:smaller"}

### ForensicFace.aggregate_embeddings

>      ForensicFace.aggregate_embeddings (embeddings, weights=None,
>                                         method='mean')

Aggregates multiple embeddings into a single embedding.

Args:
    embeddings (numpy.ndarray): A 2D array of shape (num_embeddings, embedding_dim) containing the embeddings to be
        aggregated.
    weights (numpy.ndarray, optional): A 1D array of shape (num_embeddings,) containing the weights to be assigned
        to each embedding. If not provided, all embeddings are equally weighted.

    method (str, optional): choice of agregating based on the mean or median of the embeddings. Possible values are
        'mean' and 'median'.

Returns:
    numpy.ndarray: A 1D array of shape (embedding_dim,) containing the aggregated embedding.

In [4]:
#| echo: false
#| output: asis
show_doc(ForensicFace.aggregate_from_images)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/app.py#L440){target="_blank" style="float:right; font-size:smaller"}

### ForensicFace.aggregate_from_images

>      ForensicFace.aggregate_from_images (list_of_image_paths, method='mean',
>                                          quality_weight=False)

Given a list of image paths, this method returns the average embedding of all faces found in the images.

Args:
    list_of_image_paths (List[str]): List of paths to images.
    method (str, optional): choice of agregating based on the mean or median of the embeddings. Possible values are
        'mean' and 'median'.
    quality_weight (boolean, optional): If True, use the FIQA(L) score as a weight for aggregation.

Returns:
    Union[np.ndarray, List]: If one or more faces are found, returns a 1D numpy array of shape (512,) representing the
    average embedding. Otherwise, returns an empty list.

In [ ]:
ff = ForensicFace(extended=True)

Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /home/rafael/.insightface/models/sepaelv2/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cud

In [ ]:
aggregated = ff.aggregate_from_images(["obama.png", "obama2.png"], quality_weight=True)
aggregated.shape

(512,)

## Extração de faces de vídeos com margem

In [5]:
#| echo: false
#| output: asis
show_doc(ForensicFace.extract_faces)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/app.py#L512){target="_blank" style="float:right; font-size:smaller"}

### ForensicFace.extract_faces

>      ForensicFace.extract_faces (video_path:str, dest_folder:str=None,
>                                  every_n_frames:int=1, margin:float=2.0,
>                                  start_from:float=0.0)

Extracts faces from a video and saves them as individual images.

Parameters:
    video_path (str): The path to the input video file.
    dest_folder (str, optional): The path to the output folder. If not provided, a new folder with the same name as the input video file is created.
    every_n_frames (int, optional): Extract faces from every n-th frame. Default is 1 (extract faces from all frames).
    margin (float, optional): The factor by which the detected face bounding box should be extended. Default is 2.0.
    start_from (float, optional): The time point (in seconds) after which the video frames should be processed. Default is 0.0.

Returns:
    The number of extracted faces.

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| video_path | str |  | path to video file |
| dest_folder | str | None | folder used to save extracted faces. If not provided, a new folder with the video name is created |
| every_n_frames | int | 1 | skip some frames |
| margin | float | 2.0 | margin to add to each face, w.r.t. detected bounding box |
| start_from | float | 0.0 | seconds after video start to begin processing |

In [ ]:
ff = ForensicFace()

Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /home/rafael/.insightface/models/sepaelv2/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cud

In [ ]:
ff.extract_faces(
    video_path="/home/rafael/video/video.mp4",
    start_from=0,
    every_n_frames=50,
    dest_folder="/home/rafael/video_faces",
)

/home/rafael/miniconda3/envs/ffdev/lib/python3.10/site-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


161

## Processing aligned images

In [6]:
#| echo: false
#| output: asis
show_doc(ForensicFace.process_aligned_face_image)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/app.py#L580){target="_blank" style="float:right; font-size:smaller"}

### ForensicFace.process_aligned_face_image

>      ForensicFace.process_aligned_face_image (rgb_aligned_face:numpy.ndarray)

In [ ]:
ff = ForensicFace(extended=True)

Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /home/rafael/.insightface/models/sepaelv2/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cud

In [ ]:
ret = ff.process_image_single_face("obama.png")
ret2 = ff.process_aligned_face_image(ret["aligned_face"])

/home/rafael/miniconda3/envs/ffdev/lib/python3.10/site-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4


In [ ]:
np.allclose(ret["embedding"], ret2["embedding"])

True

In [ ]:
ret["fiqa_score"], ret2["fiqa_score"]

(2.198394, 2.198394)

#