<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->

In [1]:
#| echo: false
#| output: asis
show_doc(ForensicFace)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/forensicface.py#L7){target="_blank" style="float:right; font-size:smaller"}

### ForensicFace

>      ForensicFace (model:str='sepaelv2', det_size:int=320, use_gpu:bool=True,
>                    gpu:int=0, magface=False, extended=True)

Class for processing facial images to extract useful features for forensic analysis.

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| model | str | sepaelv2 |  |
| det_size | int | 320 |  |
| use_gpu | bool | True |  |
| gpu | int | 0 | which GPU to use |
| magface | bool | False |  |
| extended | bool | True |  |

In [ ]:
ff = ForensicFace(use_gpu=True, magface=False, extended=True)

Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'arena_extend_strategy': 'kNextPowerOfTwo', 'gpu_external_empty_cache': '0', 'gpu_external_free': '0', 'cudnn_conv_use_max_workspace': '0', 'gpu_mem_limit': '18446744073709551615', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'gpu_external_alloc': '0', 'device_id': '0'}}
find model: /home/rafael/.insightface/models/sepaelv2/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'arena_extend_strategy': 'kNextPowerOfTwo', 'gpu_external_empty_cache': '0', 'gpu_external_free': '0', 'cudnn_conv_use_max_workspace': '0', 'gpu_mem_limit': '18446744073709551615', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'gpu_external_alloc': '0', 'device_id': '0'}}
find mode

In [ ]:
ff.process_image_single_face("001_frontal.jpg")

In [ ]:
results = ff.process_image_multiple_faces("tela.png")
results[0].keys(), results[0]["keypoints"], results[0]["bbox"]

(dict_keys(['keypoints', 'ipd', 'embedding', 'norm', 'bbox', 'aligned_face', 'gender', 'age', 'pitch', 'yaw', 'roll', 'fiqa_score']),
 array([[471.42807, 418.60446],
        [522.6901 , 418.05377],
        [498.82306, 449.08896],
        [479.34985, 476.44186],
        [514.3342 , 476.06934]], dtype=float32),
 array([441, 355, 548, 506]))

In [ ]:
results = ff.process_image_single_face("obama.png")
results.keys(), results["keypoints"]

(dict_keys(['keypoints', 'ipd', 'embedding', 'norm', 'bbox', 'aligned_face', 'gender', 'age', 'pitch', 'yaw', 'roll']),
 array([[103.60011, 139.88237],
        [174.2651 , 137.3372 ],
        [140.28094, 187.14757],
        [109.09432, 219.3402 ],
        [173.40782, 217.09576]], dtype=float32))

## Comparação entre duas imagens

In [2]:
#| echo: false
#| output: asis
show_doc(ForensicFace.compare)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/app.py#L405){target="_blank" style="float:right; font-size:smaller"}

### ForensicFace.compare

>      ForensicFace.compare (img1path:str, img2path:str)

Compares the similarity between two face images based on their embeddings.

Parameters:
    - img1path (str): Path to the first image file
    - img2path (str): Path to the second image file

Returns:
    A float representing the similarity score between the two faces based on their embeddings.
    The score ranges from -1.0 to 1.0, where 1.0 represents a perfect match and -1.0 represents a complete mismatch.

In [ ]:
ff.compare("obama.png", "obama2.png")

0.8555971

## Agregação de embeddings

In [3]:
#| echo: false
#| output: asis
show_doc(ForensicFace.aggregate_embeddings)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/app.py#L428){target="_blank" style="float:right; font-size:smaller"}

### ForensicFace.aggregate_embeddings

>      ForensicFace.aggregate_embeddings (embeddings, weights=None)

Aggregates multiple embeddings into a single embedding.

Args:
    embeddings (numpy.ndarray): A 2D array of shape (num_embeddings, embedding_dim) containing the embeddings to be
        aggregated.
    weights (numpy.ndarray, optional): A 1D array of shape (num_embeddings,) containing the weights to be assigned
        to each embedding. If not provided, all embeddings are equally weighted.

Returns:
    numpy.ndarray: A 1D array of shape (embedding_dim,) containing the aggregated embedding.

In [4]:
#| echo: false
#| output: asis
show_doc(ForensicFace.aggregate_from_images)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/app.py#L449){target="_blank" style="float:right; font-size:smaller"}

### ForensicFace.aggregate_from_images

>      ForensicFace.aggregate_from_images (list_of_image_paths)

Given a list of image paths, this method returns the average embedding of all faces found in the images.

Args:
    list_of_image_paths (List[str]): List of paths to images.

Returns:
    Union[np.ndarray, List]: If one or more faces are found, returns a 1D numpy array of shape (512,) representing the
    average embedding. Otherwise, returns an empty list.

In [ ]:
aggregated = ff.aggregate_from_images(["obama.png", "obama2.png"])
aggregated.shape

(512,)

## Suporte a MagFace

Para utilizar, instancie o forensicface com a opção magface = True:

``ff = forensicface(magface=True)``

Modelo de [MagFace](https://github.com/IrvingMeng/MagFace)

In [ ]:
ff = ForensicFace(det_size=320, use_gpu=True, magface=True)
good = ff.process_image("001_frontal.JPG")
bad = ff.process_image("001_cam1_1.jpg")
good["magface_norm"], bad["magface_norm"]

Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'arena_extend_strategy': 'kNextPowerOfTwo', 'gpu_external_empty_cache': '0', 'gpu_external_free': '0', 'cudnn_conv_use_max_workspace': '0', 'gpu_mem_limit': '18446744073709551615', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'gpu_external_alloc': '0', 'device_id': '0'}}
find model: /home/rafael/.insightface/models/sepaelv2/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'arena_extend_strategy': 'kNextPowerOfTwo', 'gpu_external_empty_cache': '0', 'gpu_external_free': '0', 'cudnn_conv_use_max_workspace': '0', 'gpu_mem_limit': '18446744073709551615', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'gpu_external_alloc': '0', 'device_id': '0'}}
find mode

(23.233418, 22.57745)

## Extração de faces de vídeos com margem

In [5]:
#| echo: false
#| output: asis
show_doc(ForensicFace.extract_faces)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/app.py#L510){target="_blank" style="float:right; font-size:smaller"}

### ForensicFace.extract_faces

>      ForensicFace.extract_faces (video_path:str, dest_folder:str=None,
>                                  every_n_frames:int=1, margin:float=2.0,
>                                  start_from:float=0.0)

Extracts faces from a video and saves them as individual images.

Parameters:
    video_path (str): The path to the input video file.
    dest_folder (str, optional): The path to the output folder. If not provided, a new folder with the same name as the input video file is created.
    every_n_frames (int, optional): Extract faces from every n-th frame. Default is 1 (extract faces from all frames).
    margin (float, optional): The factor by which the detected face bounding box should be extended. Default is 2.0.
    start_from (float, optional): The time point (in seconds) after which the video frames should be processed. Default is 0.0.

Returns:
    The number of extracted faces.

|    | **Type** | **Default** | **Details** |
| -- | -------- | ----------- | ----------- |
| video_path | str |  | path to video file |
| dest_folder | str | None | folder used to save extracted faces. If not provided, a new folder with the video name is created |
| every_n_frames | int | 1 | skip some frames |
| margin | float | 2.0 | margin to add to each face, w.r.t. detected bounding box |
| start_from | float | 0.0 | seconds after video start to begin processing |

In [ ]:
ff = ForensicFace()

In [ ]:
ff.extract_faces(
    video_path="/home/rafael/productionID_3762907.mp4",
    start_from=0,
    every_n_frames=10,
    dest_folder="/home/rafael/video_faces",
)