<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->

In [1]:
#| echo: false
#| output: asis
show_doc(cosine_similarity)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/utils.py#L10){target="_blank" style="float:right; font-size:smaller"}

### cosine_similarity

>      cosine_similarity (X, Z)

In [2]:
#| echo: false
#| output: asis
show_doc(compute_ss_ds)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/utils.py#L22){target="_blank" style="float:right; font-size:smaller"}

### compute_ss_ds

>      compute_ss_ds (X, x_id, x_names=None, Z=None, z_id=None, z_names=None)

*Compute cosine similarities between the cartesian product of two arrays X and Z and
return same-source (ss) and different-source (ds) scores.
If only the array X and x_id are provided, compute the cosine similarities between all pairwise
combination in X. Also return the names of the files associated with each score, is x_names and z_names are provided.

Inputs:
    X, Z: 2d numpy arrays with embeddings (1 per line)
    x_id, z_id: 1d numpy arrays with identity labels
    x_names, z_names: 1d numpy arrays with names of files associated with the embeddings

Returns:
    scores: 1d numpy array with scores
    y: 1d numpy arrays with ss (1) and ds (0) labels to the scores array
    names: list of tuples with names of files associated with each score*

In [ ]:
# Example usage
X = np.random.rand(4, 128)  # 4 embeddings of dimension 128
x_id = np.array([0, 0, 1, 1])  # Identity labels
x_names = np.array(["0_a.jpg", "0_b.jpg", "1_a.jpg", "1_b.jpg"])

Z = np.random.rand(4, 128)  # 4 embeddings of dimension 128
z_id = np.array([0, 1, 1, 2])  # Identity labels
z_names = np.array(["0_c.jpg", "1_c.jpg", "1_d.jpg", "2_a.jpg"])

scores, y, names = compute_ss_ds(
    X=X, x_id=x_id, x_names=x_names, Z=Z, z_id=z_id, z_names=z_names
)
scores, y, names

(array([0.7261676 , 0.76134557, 0.78772832, 0.76922003, 0.74130075,
        0.75798372, 0.77273163, 0.75997033, 0.76467846, 0.71801777,
        0.75326126, 0.73211696, 0.72354578, 0.78339759, 0.74410164,
        0.74325012]),
 array([1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 [('0_a.jpg', '0_c.jpg'),
  ('0_b.jpg', '0_c.jpg'),
  ('1_a.jpg', '1_c.jpg'),
  ('1_a.jpg', '1_d.jpg'),
  ('1_b.jpg', '1_c.jpg'),
  ('1_b.jpg', '1_d.jpg'),
  ('0_a.jpg', '1_c.jpg'),
  ('0_a.jpg', '1_d.jpg'),
  ('0_a.jpg', '2_a.jpg'),
  ('0_b.jpg', '1_c.jpg'),
  ('0_b.jpg', '1_d.jpg'),
  ('0_b.jpg', '2_a.jpg'),
  ('1_a.jpg', '0_c.jpg'),
  ('1_a.jpg', '2_a.jpg'),
  ('1_b.jpg', '0_c.jpg'),
  ('1_b.jpg', '2_a.jpg')])

In [ ]:
scores, y, names = compute_ss_ds(X=X, x_id=x_id, Z=Z, z_id=z_id)
scores, y, names

(array([0.7261676 , 0.76134557, 0.78772832, 0.76922003, 0.74130075,
        0.75798372, 0.77273163, 0.75997033, 0.76467846, 0.71801777,
        0.75326126, 0.73211696, 0.72354578, 0.78339759, 0.74410164,
        0.74325012]),
 array([1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 None)

In [ ]:
scores, y, names = compute_ss_ds(X=X, x_id=x_id, x_names=x_names)
scores, y, names

(array([0.75920622, 0.77365152, 0.76394119, 0.78708138, 0.75681996,
        0.79128601]),
 array([1., 1., 0., 0., 0., 0.]),
 [('0_a.jpg', '0_b.jpg'),
  ('1_a.jpg', '1_b.jpg'),
  ('0_a.jpg', '1_a.jpg'),
  ('0_a.jpg', '1_b.jpg'),
  ('0_b.jpg', '1_a.jpg'),
  ('0_b.jpg', '1_b.jpg')])

In [ ]:
scores, y, names = compute_ss_ds(X=X, x_id=x_id)
scores, y, names

(array([0.75920622, 0.77365152, 0.76394119, 0.78708138, 0.75681996,
        0.79128601]),
 array([1., 1., 0., 0., 0., 0.]),
 None)

> Export the Python version and the packages names and versions in the active virtual environment

In [3]:
#| echo: false
#| output: asis
show_doc(freeze_env)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/utils.py#L81){target="_blank" style="float:right; font-size:smaller"}

### freeze_env

>      freeze_env ()

In [ ]:
# example usage

freeze_env()

{'Python version': '3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0]',
 'albumentations': '1.3.1',
 'asttokens': '2.2.1',
 'astunparse': '1.6.3',
 'backcall': '0.2.0',
 'backports.functools-lru-cache': '1.6.4',
 'bleach': '6.0.0',
 'certifi': '2023.5.7',
 'cffi': '1.15.1',
 'charset-normalizer': '3.1.0',
 'coloredlogs': '15.0.1',
 'contourpy': '1.1.0',
 'cryptography': '41.0.1',
 'cycler': '0.11.0',
 'Cython': '0.29.35',
 'debugpy': '1.5.1',
 'decorator': '5.1.1',
 'docutils': '0.20.1',
 'easydict': '1.10',
 'entrypoints': '0.4',
 'execnb': '0.1.5',
 'executing': '1.2.0',
 'fastcore': '1.5.29',
 'flatbuffers': '23.5.26',
 'fonttools': '4.40.0',
 'forensicface': '0.3.5',
 'ghapi': '1.0.4',
 'humanfriendly': '10.0',
 'idna': '3.4',
 'imageio': '2.31.1',
 'importlib-metadata': '6.7.0',
 'imutils': '0.5.4',
 'insightface': '0.7.3',
 'ipykernel': '6.15.0',
 'ipython': '8.14.0',
 'jaraco.classes': '3.2.3',
 'jedi': '0.18.2',
 'jeepney': '0.8.0',
 'joblib': '1.2.0',
 'jupyter-client': '7.3.

In [4]:
#| echo: false
#| output: asis
show_doc(transform_keypoints)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/utils.py#L100){target="_blank" style="float:right; font-size:smaller"}

### transform_keypoints

>      transform_keypoints (keypoints, M)

*Transforms keypoints from the original image space to the aligned image space.

Args:
    keypoints (numpy array): A 2D array of shape (5, 2) representing the original keypoints.
    M (numpy array): The 2x3 affine transformation matrix.

Returns:
    numpy array: A 2D array of shape (5, 2) representing the transformed keypoints.*

In [5]:
#| echo: false
#| output: asis
show_doc(annotate_img_with_kps)

---

[source](https://github.com/rafribeiro/forensicface/blob/main/forensicface/utils.py#L117){target="_blank" style="float:right; font-size:smaller"}

### annotate_img_with_kps

>      annotate_img_with_kps (bgr_img:numpy.ndarray, kps:numpy.ndarray,
>                             color:str='red', radius:int=2)

*Annotate an image with keypoints.

Parameters:
bgr_img (numpy.ndarray): The input image in BGR format.
kps (numpy.ndarray): A numpy array of shape (5, 2) containing the keypoints.
color (str, optional): The color of the keypoints. Default is 'red'.
                    Options are 'red', 'blue', 'green', 'white', 'black'.
radius (int, optional): The radius of the keypoints. Default is 2.

Returns:
numpy.ndarray: The image with keypoints annotated.*